#version 460
#extension GL_EXT_buffer_reference : require

#include "Application/ShaderRendererTypes.incl"
#include "Application/shading.glsl"
#include "TestShaderTypes.incl"

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

BUFFER_POINTER(VoidBuffer, bool);
BUFFER_POINTER(FresnelSchlickInputBufer, FresnelSchlickInput);
BUFFER_POINTER(FresnelSchlickOutputBufer, FresnelSchlickOutput);

layout(push_constant, std430) uniform PushConstantLayout {
    VoidBuffer pc_InputBuffer;
    VoidBuffer pc_OutputBuffer;
};

void testFresnelSchlick(uint index)
{
    FresnelSchlickInputBufer inputBuffer = FresnelSchlickInputBufer(pc_InputBuffer);
    FresnelSchlickOutputBufer outputBuffer = FresnelSchlickOutputBufer(pc_OutputBuffer);

    outputBuffer.v[index].result = fresnelSchlick(inputBuffer.v[index].theta, inputBuffer.v[index].f0);
}

void main() 
{
    const uint index = gl_GlobalInvocationID.x;

    testFresnelSchlick(index);
}